AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
