require_relative 'TicTacToe/version'
# require_relative './..//set_languages'
require_relative './user_interface'
require_relative './validation'
require_relative './game_status'
require_relative './game_engine'
require_relative './board'
require_relative './players/human'
require_relative './players/intelligent_computer'
require_relative './express_board_in_rows'
require_relative '../config/env_variables'
# require_relative '../config/game_interface'
require_relative '../hello/test'
# require_relative '../config/game_set_up'
# SetLanguages.change_language('fr')
# GameInterface.display_language_options
