require_relative './tic_tac_toe/version'
require_relative './tic_tac_toe/game_config/set_languages'
require_relative './tic_tac_toe/user_interface'
require_relative './tic_tac_toe/validation'
require_relative './tic_tac_toe/game_status'
require_relative './tic_tac_toe/game_engine'
require_relative './tic_tac_toe/board'
require_relative './tic_tac_toe/players/human'
require_relative './tic_tac_toe/players/intelligent_computer'
require_relative './tic_tac_toe/express_board_in_rows'
require_relative '../config/env_variables'
require_relative './tic_tac_toe/game_config/game_interface'
require_relative './tic_tac_toe/game_config/game_set_up'
require_relative './tic_tac_toe/web_engine'
require_relative './tic_tac_toe/opponent_type'

