require_relative 'TicTacToe/version'
require_relative './../config/set_languages'
require_relative './user_interface'
require_relative './validation'
require_relative './game_status'
require_relative 'game_engine'
require_relative './board'
require_relative './players/human'
require_relative './players/intelligent_computer'

