#!/usr/bin/env ruby
require_relative '../config/set_languages'
require_relative '../config/game_interface'
require_relative '../config/game_set_up'
require_relative '../config/env_variables'

SetLanguages.change_language
# system('clear')
GameInterface.display_instructions
game_on = true
while game_on
  choice = GameInterface.choose_mode
  game = GameSetUp.setup(choice)
  game.play
  puts I18n.t('prompt_continue_or_exit_game')
  choice = gets.chomp
  game_on = choice.downcase == 'y'
  system('clear')
end
